version: '3'

services:
  treeserve:
    image: mercury/treeserve
    volumes:
      - ./input.gz:/docker/input.gz
      - ./group:/etc/group
      - ./passwd:/etc/passwd
    restart: always
    ports:
      - "8080:80"
    networks: [apps]
  frontend:
    image: nginx
    volumes:
      - ./hgi-reports/lustre_reports:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks: [apps]

networks:
  apps:
    ipam:
      driver: default
      config:
        - subnet: 10.9.1.1/24
