version: '3'

services:
  treeserve:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input.gz:/docker/input.gz
    restart: always
    ports:
      - "8080:8080"
    networks: [apps]
  frontend:
    image: nginx
    volumes: 
      - ./hgi-reports/lustre_reports:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "80:80"
    networks: [apps]

networks:
  apps:
    ipam:
      driver: default
      config:
        - subnet: 10.9.1.1/24
